# Generated by Django 5.2.4 on 2025-08-04 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_users_options_alter_users_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='email_verify',
            field=models.BooleanField(default=True, verbose_name='Проверка почты'),
        ),
        migrations.AddField(
            model_name='users',
            name='token',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Токен'),
        ),
    ]
