# Generated by Django 5.2.4 on 2025-07-28 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LinkService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('full_name', models.CharField(help_text='Введите Фамилию, имя, отчество', max_length=300, verbose_name='ФИО')),
                ('comment', models.TextField(blank=True, help_text='Комментарии', null=True)),
            ],
        ),
    ]
