# Generated by Django 5.2.4 on 2025-07-29 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_message', models.CharField(help_text='Введите тему письма', max_length=300, verbose_name='Тема письма')),
                ('text_message', models.TextField(help_text='Введите текст письма', verbose_name='Текс пиьсма')),
            ],
        ),
    ]
