# Generated by Django 5.2.4 on 2025-07-29 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0003_malling'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mailjurnal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_spam', models.DateTimeField(auto_now_add=True, verbose_name='Время попытки рассылки')),
                ('status', models.CharField(choices=[('успешно', 'Успешно'), ('не_успешно', 'Не успешно')], max_length=20, verbose_name='статус рассылки')),
                ('server_response', models.TextField(blank=True, null=True, verbose_name='Ответ сервера')),
                ('spam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailing.malling', verbose_name='Рассылка')),
            ],
        ),
    ]
