# Generated by Django 5.2.4 on 2025-07-29 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0004_mailjurnal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mailjurnal',
            old_name='spam',
            new_name='malling',
        ),
        migrations.RenameField(
            model_name='mailjurnal',
            old_name='time_spam',
            new_name='time_malling',
        ),
    ]
