# Generated by Django 5.2.4 on 2025-08-01 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0005_rename_spam_mailjurnal_malling_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='text_message',
            field=models.TextField(help_text='Введите текст письма', verbose_name='Текс пиcьма'),
        ),
    ]
