# Generated by Django 5.2.4 on 2025-08-01 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0006_alter_message_text_message'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LinkService',
            new_name='Client',
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
    ]
