# Generated by Django 5.2.4 on 2025-08-02 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0007_rename_linkservice_client_alter_client_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='comment',
            field=models.TextField(blank=True, help_text='Комментарии', null=True, verbose_name='Комментарии'),
        ),
    ]
