# Generated by Django 5.2.4 on 2025-08-03 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0009_client_user_message_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Malling',
            new_name='Mailing',
        ),
    ]
