# Generated by Django 5.2.4 on 2025-08-03 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0010_rename_malling_mailing'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailjurnal',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mailing.client', verbose_name='Получатель'),
        ),
    ]
