# Generated by Django 5.2.4 on 2025-08-04 18:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0011_mailjurnal_client'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailing',
            options={'verbose_name': 'Рассылка', 'verbose_name_plural': 'Рассылки'},
        ),
        migrations.AlterModelOptions(
            name='mailjurnal',
            options={'verbose_name': 'Журнал рассылки', 'verbose_name_plural': 'Журналы рассылок'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': 'Сообщение', 'verbose_name_plural': 'Сообщения'},
        ),
        migrations.AddField(
            model_name='mailjurnal',
            name='successful_attempts',
            field=models.IntegerField(default=0, verbose_name='Успешные попытки'),
        ),
        migrations.AddField(
            model_name='mailjurnal',
            name='unsuccessful_attempts',
            field=models.IntegerField(default=0, verbose_name='Неуспешные попытки'),
        ),
        migrations.AddField(
            model_name='mailjurnal',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
