# Generated by Django 5.2.4 on 2025-08-04 18:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0012_alter_mailing_options_alter_mailjurnal_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailjurnal',
            name='successful_attempts',
        ),
        migrations.RemoveField(
            model_name='mailjurnal',
            name='unsuccessful_attempts',
        ),
        migrations.AddField(
            model_name='mailing',
            name='user',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='mailings', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='MailingReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='Время отчета')),
                ('successful_attempts', models.IntegerField(default=0, verbose_name='Успешные попытки')),
                ('unsuccessful_attempts', models.IntegerField(default=0, verbose_name='Неуспешные попытки')),
                ('mailing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailing.mailing', verbose_name='Рассылка')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Отчет по рассылке',
                'verbose_name_plural': 'Отчеты по рассылкам',
            },
        ),
    ]
