# Generated by Django 5.2.4 on 2025-08-04 19:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0013_remove_mailjurnal_successful_attempts_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mailingreport',
            unique_together={('mailing', 'user')},
        ),
    ]
